log_sign_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'log_sign_app'
urlpatterns = [
    url('register/',views.register,name='register'),
    url('user_login/',views.user_login, name='user_login'),
]

registeration/urls.py
from django.contrib import admin
from django.urls import path,include
from log_sign_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name='index'),
    path('log_sign/', include('log_sign_app.urls')),
    path('logout/',views.user_logout, name='logout'),
    path('special/',views.special, name='special')
]

log_sign_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserModelProfile(models.Model):
    user = models.OneToOneField(User, on_delete='models.CASCADE')
    #additional
    portfolio_site = models.URLField(blank=True)

    portfile_pic   = models.ImageField(upload_to="pics" , blank=True)

    def __str__(self):
        return self.user

log_sign_app/forms.py
from django import forms
from django.contrib.auth.models import User
from . models import UserModelProfile

class UserForm(forms.ModelForm):
    class Meta():
        model = User
        fields = ['username','email','password']
        widgets = {
        'password':forms.PasswordInput(),
        }

class UserModelProfileForm(forms.ModelForm):
    class Meta():
        model = UserModelProfile
        fields = ['portfolio_site','portfile_pic']
    

log_sign_app/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from . forms import UserForm,UserModelProfileForm
from django.contrib.auth import authenticate,login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request,'index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in ")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method ==  'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserModelProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserModelProfileForm()

    return render(request,'registeration/register.html',{'user_form':user_form,
                                                         'profile_form':profile_form,
                                                         'registered':registered})



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse(reverse('Account Not Active'))
        else:
            print("Someone tried to login in")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid login details supplied ")
    else:
        return render(request,'registeration/login.html',{})

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'admin:index' %}">DJANGO</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">admin</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'log_sign_app:register' %}">register</a>
            </li>

            {% if user.is_authenticated %}
            <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
            {% else %}
            <li><a class="nav-link" href="{% url 'log_sign_app:user_login' %}">Login</a></li>
            {%endif%}
          </ul>
        </div>
      </nav>
      {% block register %}
      {% endblock %}
      
      {% block content %}
      {% endblock %}

      {% block body_block%}
      {% endblock%}
    </div>
  </body>
</html>

templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% block content %}
{% endblock %}

templates/registeration/login.html
{% extends "base.html" %}
{% block body_block %}
<h1>Login here</h1>
<form  action="{% url 'log_sign_app:user_login' %}" method="post">
  {% csrf_token %}
  <label for="username">Username:</label>
  <input type="text" name="username">

  <label for="password">Password:</label>
  <input type="password" name="password" value="">

  <input type="submit" name="" value="login">

</form>
{% endblock %}

templates/registeration/register.html
{% extends "base.html" %}
{% load staticfiles %}
{% block register %}
<div class="just">
  {% if registered %}
  <h1>Thank you for registeration</h1>
  {% else %}
  <h1>register here </h1>
  <form  enctype="multipart/form-data"  method="post">
    {% csrf_token %}
    {{ user_form.as_p}}
    {{ profile_form.as_p}}
    <input type="submit" name="" value="submit" id='submit_form'>
  </form>
  {% endif %}
</div>
{% endblock %}